import type { ManualChunk } from "@/lib/forms/official-policy-manual";

/**
 * ============================================================================
 * THE JBA POLICY MANUAL EDITED 5.2025, AS THE KNOWLEDGE BASE HOLDS IT
 * ============================================================================
 *
 * All 110 chunks of the indexed manual (document version 2), exported from the
 * knowledge tables: the real chunk index, PDF sheet, printed page, locator and
 * the section headings ingestion recorded in `metadata.sections`.
 *
 * CONTENT IS TRUNCATED, NEVER REWORDED. The table-of-contents chunks keep
 * enough of their text to be recognised as contents pages; the Smoking/Vaping,
 * Attendance and Seminar/Webinar Attendance chunks are kept whole because the
 * regression tests are about them; every other chunk keeps its opening only.
 *
 * `chunkId` is a stand-in — the real ids are database uuids and nothing here
 * depends on their value.
 */
export const JBA_MANUAL_DOCUMENT = {
  id: "f527da34-a25b-413c-93a4-31e3f1c946d3",
  title: "JBA Policy Manual Edited 5.2025",
  category: "operations",
} as const;

export const JBA_MANUAL_CHUNKS: readonly ManualChunk[] = [
  {
    chunkIndex: 0,
    chunkId: "jba-0",
    page: 1,
    printedPage: null,
    locator: "Page 1",
    section: null,
    sections: [],
    content: "2025\nJB & Associates\nEmployment Policy\nManual\nREVISED MAY 2025\nINCLUDES ALL BRANDS OPERATED BY JB & ASSOCIATES, INC, HERIN\nREFFERRED TO AS “THE COMPANY\"",
  },
  {
    chunkIndex: 1,
    chunkId: "jba-1",
    page: 1,
    printedPage: null,
    locator: "Page 1",
    section: null,
    sections: [],
    content: "1 | P a g e\nThe Company Employment Policy Manual\nThis manual is designed to acquaint and provide employees with information about working conditions,\nEmployee b",
  },
  {
    chunkIndex: 2,
    chunkId: "jba-2",
    page: 3,
    printedPage: 2,
    locator: "Page 2 — Table of Contents",
    section: "Table of Contents",
    sections: [
      { heading: "Table of Contents", page: 2 },
    ],
    content: "2 | P a g e\nTable of Contents\nThe Company Employment Policy Manual ..........................................................................................1\nReference List ....................................................................................................................................6\nCore Values ....................................................................................................",
  },
  {
    chunkIndex: 3,
    chunkId: "jba-3",
    page: 3,
    printedPage: 2,
    locator: "Page 2",
    section: null,
    sections: [],
    content: "8\nDisability Accommodation-Americans with Disability Act ........................................................................\n\n9\nSexual and Other Forms of Harassment ................................................................................................... 9\nDrug, Alcohol and Smoking Policy........................................................................................................... 11\nStand",
  },
  {
    chunkIndex: 4,
    chunkId: "jba-4",
    page: 3,
    printedPage: 2,
    locator: "Page 2",
    section: null,
    sections: [],
    content: "15\nCrunch Fitness Specific Dress Code: ...................................................................................................\n\n16\nBuff City Soap: ..................................................................................................................................... 16\nSun Tan City: ..............................................................................................................",
  },
  {
    chunkIndex: 5,
    chunkId: "jba-5",
    page: 3,
    printedPage: 2,
    locator: "Page 2",
    section: null,
    sections: [],
    content: "19\nCoupon Collection ...................................................................................................................................\n\n19\nCell Phone/Smart Watch Policy .............................................................................................................. 19\nCompany Email Account .................................................................................................",
  },
  {
    chunkIndex: 6,
    chunkId: "jba-6",
    page: 4,
    printedPage: 3,
    locator: "Page 3",
    section: null,
    sections: [],
    content: "3 | P a g e\nPoint of Sale and Alarm Passwords......................................................................................................... 20\nEmployment Verification ........................................................................................................................ 20\nOutside Employment ...................................................................................................",
  },
  {
    chunkIndex: 7,
    chunkId: "jba-7",
    page: 4,
    printedPage: 3,
    locator: "Page 3",
    section: null,
    sections: [],
    content: "21\nBackground Checks .................................................................................................................................\n\n21\nBusiness Ethics ........................................................................................................................................ 21\nCommunication and Confidentiality Policies ..................................................................",
  },
  {
    chunkIndex: 8,
    chunkId: "jba-8",
    page: 4,
    printedPage: 3,
    locator: "Page 3",
    section: null,
    sections: [],
    content: "23\nCommunications Systems Policy.............................................................................................................\n\n24\nInformation Technology Support ............................................................................................................ 24\nSafety in the Workplace ...........................................................................................................",
  },
  {
    chunkIndex: 9,
    chunkId: "jba-9",
    page: 4,
    printedPage: 3,
    locator: "Page 3",
    section: null,
    sections: [],
    content: "28\nVisitors in the Workplace ........................................................................................................................\n\n29\nAnimals in the Workplace ....................................................................................................................... 30\nRobberies ............................................................................................................",
  },
  {
    chunkIndex: 10,
    chunkId: "jba-10",
    page: 5,
    printedPage: 4,
    locator: "Page 4",
    section: null,
    sections: [],
    content: "4 | P a g e\nHandling Theft......................................................................................................................................... 30\nProper Use of General Operating Equipment ......................................................................................... 31\nWet Floor Sign .......................................................................................................",
  },
  {
    chunkIndex: 11,
    chunkId: "jba-11",
    page: 5,
    printedPage: 4,
    locator: "Page 4",
    section: null,
    sections: [],
    content: "33\nOrientation ..............................................................................................................................................\n\n33\nIntroductory Period (Probationary Period) ............................................................................................. 33\nEvaluations and Raises ................................................................................................",
  },
  {
    chunkIndex: 12,
    chunkId: "jba-12",
    page: 5,
    printedPage: 4,
    locator: "Page 4",
    section: null,
    sections: [],
    content: "36\nAccessing W-2’s.......................................................................................................................................\n\n36\nTimekeeping & Payroll ..................................................................................................................... 36\nTime Records...........................................................................................................",
  },
  {
    chunkIndex: 13,
    chunkId: "jba-13",
    page: 5,
    printedPage: 4,
    locator: "Page 4",
    section: null,
    sections: [],
    content: "38\nPayroll Deductions ..................................................................................................................................\n\n39\nGarnishment of Employee Wages .......................................................................................................... 39\nTravel time/cost reimbursements (for travel NOT requiring overnight stays) ....................................... 39\nOvern",
  },
  {
    chunkIndex: 14,
    chunkId: "jba-14",
    page: 6,
    printedPage: 5,
    locator: "Page 5",
    section: null,
    sections: [],
    content: "5 | P a g e\nError in Pay.............................................................................................................................................. 40\nFair Labor Standard Act (FSLA) – Safe Harbor Policy .............................................................................. 40\nSalary Administration...............................................................................................",
  },
  {
    chunkIndex: 15,
    chunkId: "jba-15",
    page: 6,
    printedPage: 5,
    locator: "Page 5",
    section: null,
    sections: [],
    content: "45\nGroup Health Plan Continuation Coverage Under COBRA .....................................................................\n\n45\n401K Benefit ............................................................................................................................................ 45\nLeave Requests .......................................................................................................................",
  },
  {
    chunkIndex: 16,
    chunkId: "jba-16",
    page: 6,
    printedPage: 5,
    locator: "Page 5",
    section: null,
    sections: [],
    content: "48\nClient Tanning Policies and Regulations (STC & Crunch ONLY) ...........................................................\n\n48\nProtecting the Client from Overexposing ............................................................................................... 48\nConsent Forms (New Client Release Forms) ........................................................................................... 49\nEye Protection ...",
  },
  {
    chunkIndex: 17,
    chunkId: "jba-17",
    page: 7,
    printedPage: 6,
    locator: "Page 6 — Reference List",
    section: "Reference List",
    sections: [
      { heading: "Reference List", page: 6 },
      { heading: "Leadership Team", page: 6 },
      { heading: "Support Center", page: 6 },
      { heading: "Maintenance Team", page: 6 },
    ],
    content: "6 | P a g e\nReference List\nLincoln Support Center Telephone: 402-488-8261\nLeadership Team\nCurt Bowen Owner Curt.Bowen@Glowbrands.com\nMarissa Lempka Executive VP",
  },
  {
    chunkIndex: 18,
    chunkId: "jba-18",
    page: 8,
    printedPage: 7,
    locator: "Page 7 — Core Values",
    section: "Core Values",
    sections: [
      { heading: "Core Values", page: 7 },
      { heading: "Our Culture", page: 7 },
      { heading: "Work Policies & Regulations", page: 7 },
      { heading: "At-Will Employment", page: 7 },
    ],
    content: "7 | P a g e\nCore Values\nNothing’s Impossible\n• The answers are out there, it’s up to us to find it.\nWork Hard, Have Fun\n• If you make work fun, it wont feel lik",
  },
  {
    chunkIndex: 19,
    chunkId: "jba-19",
    page: 9,
    printedPage: 8,
    locator: "Page 8 — Equal Employment Opportunity",
    section: "Equal Employment Opportunity",
    sections: [
      { heading: "Equal Employment Opportunity", page: 8 },
    ],
    content: "8 | P a g e\nat will at any time, with or without notice or cause, so long as there is no violation of applicable\nfederal or state law. Policies set forth in thi",
  },
  {
    chunkIndex: 20,
    chunkId: "jba-20",
    page: 9,
    printedPage: 8,
    locator: "Page 8 — Open Door Policy",
    section: "Open Door Policy",
    sections: [
      { heading: "Open Door Policy", page: 8 },
      { heading: "Immigration Law Compliance", page: 8 },
    ],
    content: "Anyone who believes this policy has been violated may report this violation to the Human\nResources Department.\n\nOpen Door Policy\nEvery Employee is encouraged to",
  },
  {
    chunkIndex: 21,
    chunkId: "jba-21",
    page: 10,
    printedPage: 9,
    locator: "Page 9 — Disability Accommodation-Americans with Disability Act",
    section: "Disability Accommodation-Americans with Disability Act",
    sections: [
      { heading: "Disability Accommodation-Americans with Disability Act", page: 9 },
    ],
    content: "9 | P a g e\nEmployees with questions or seeking more information on immigration law issues are\nencouraged to contact Human Resources. Employees may raise questi",
  },
  {
    chunkIndex: 22,
    chunkId: "jba-22",
    page: 10,
    printedPage: 9,
    locator: "Page 9 — Sexual and Other Forms of Harassment",
    section: "Sexual and Other Forms of Harassment",
    sections: [
      { heading: "Sexual and Other Forms of Harassment", page: 9 },
    ],
    content: "However, the employee may still be deemed disabled under ADA.\n\nAdditionally, impairments\nmay now be of short duration, intermittent, or episodic and still quali",
  },
  {
    chunkIndex: 23,
    chunkId: "jba-23",
    page: 11,
    printedPage: 10,
    locator: "Page 10",
    section: null,
    sections: [],
    content: "10 | P a g e\no VERBAL HARASSMENT: including sexual innuendoes, suggestive comments, jokes of a sexual\nnature, sexual propositions, and threats. o NON-VERBAL HAR",
  },
  {
    chunkIndex: 24,
    chunkId: "jba-24",
    page: 11,
    printedPage: 10,
    locator: "Page 10",
    section: null,
    sections: [],
    content: "Employees may reserve the\nright to notify local authorities if they feel threatened and if they are of the belief that laws have been\nviolated.\n\nEx: Terroristic",
  },
  {
    chunkIndex: 25,
    chunkId: "jba-25",
    page: 12,
    printedPage: 11,
    locator: "Page 11 — Drug, Alcohol and Smoking Policy",
    section: "Drug, Alcohol and Smoking Policy",
    sections: [
      { heading: "Drug, Alcohol and Smoking Policy", page: 11 },
    ],
    content: "11 | P a g e\nDrug, Alcohol and Smoking Policy\nIn compliance with the Drug-Free Workplace Act of 1988, The Company has a longstanding\ncommitment to provide a saf",
  },
  {
    chunkIndex: 26,
    chunkId: "jba-26",
    page: 12,
    printedPage: 11,
    locator: "Page 11 — Prescribed Medications",
    section: "Prescribed Medications",
    sections: [
      { heading: "Prescribed Medications", page: 11 },
    ],
    content: "o The presence of any detectable number of prohibited substances in the Employee's system\nwhile at work or while on Company premises.\n\n\"Prohibited substances\" i",
  },
  {
    chunkIndex: 27,
    chunkId: "jba-27",
    page: 13,
    printedPage: 12,
    locator: "Page 12 — Smoking/Vaping",
    section: "Smoking/Vaping",
    sections: [
      { heading: "Smoking/Vaping", page: 12 },
    ],
    content: "12 | P a g e\no Any medications that inhibit an Employee’s ability to perform their job duties safely and\neffectively must be reported to the Human Resource Department prior to their next working\nday for further review and possible job duty modifications (if applicable). Smoking/Vaping\no Our business is focused on health, and we have several policies affecting the possession and\nuse of all tobacco products and nicotine products, including but not limited to cigarettes,\nvapor cigarettes, and chewing tobacco while working, or while on the premises. o The Company adheres to all federal, state, local rules regarding smoking in the workplace. Smoking or use of “vapor” products are not permitted in any of the locations. All locations,\nincluding but not limited to all facilities and parking areas and company owned or leased\nvehicles are smoke and vapor free. Employees who smoke or use “vapor” products shall do\nso off the premises, including the parking lots. The Company reserves the right to undertake monitored drug and/or alcohol testing as follows:\no RANDOM TESTING: Employees may be selected at random for drug and/or alcohol testing at\nany interval determined by The Company. This test may be monitored/observed when\nadministered.",
  },
  {
    chunkIndex: 28,
    chunkId: "jba-28",
    page: 13,
    printedPage: 12,
    locator: "Page 12 — Standards of Conduct",
    section: "Standards of Conduct",
    sections: [
      { heading: "Standards of Conduct", page: 12 },
    ],
    content: "This test may be monitored/observed when\nadministered.\n\no FOR-CAUSE TESTING: The Company may ask an Employee to submit to a drug and/or alcohol\ntest at any time",
  },
  {
    chunkIndex: 29,
    chunkId: "jba-29",
    page: 13,
    printedPage: 12,
    locator: "Page 12 — Standards of Conduct",
    section: "Standards of Conduct",
    sections: [
      { heading: "Standards of Conduct", page: 12 },
    ],
    content: "Standards of Conduct\nThe Company expects Employees to follow rules of conduct that will protect the interests and\nsafety of all customers, Employees, and The Co",
  },
  {
    chunkIndex: 30,
    chunkId: "jba-30",
    page: 14,
    printedPage: 13,
    locator: "Page 13",
    section: null,
    sections: [],
    content: "13 | P a g e\no Lack of sales performance\no Indecent or immoral behavior\no Conduct that requires investigation due to its negative impact on The Company’s public",
  },
  {
    chunkIndex: 31,
    chunkId: "jba-31",
    page: 14,
    printedPage: 13,
    locator: "Page 13",
    section: null,
    sections: [],
    content: "o Fighting or threatening violence in the workplace\no Boisterous or disruptive activity in the workplace\no Threatened or actual injury of another Employee or cu",
  },
  {
    chunkIndex: 32,
    chunkId: "jba-32",
    page: 15,
    printedPage: 14,
    locator: "Page 14 — Disciplinary Action",
    section: "Disciplinary Action",
    sections: [
      { heading: "Disciplinary Action", page: 14 },
    ],
    content: "14 | P a g e\no Undisclosed and/or unauthorized photography, video recording, or sound recording of oral,\nor telephone communication, in which a customer, Employ",
  },
  {
    chunkIndex: 33,
    chunkId: "jba-33",
    page: 15,
    printedPage: 14,
    locator: "Page 14 — Attendance",
    section: "Attendance",
    sections: [
      { heading: "Attendance", page: 14 },
    ],
    content: "Employment with The Company is based on mutual\nconsent and both the employee, and The Company have the right to terminate employment as\nwill, with or without cause or advance notice.\n\nThe Company may use progressive discipline at its\ndiscretion. Attendance\nIt is the responsibility of each employee to know his or her work schedule and to always be on\ntime. Lack of punctuality or absenteeism has a negative impact on everyone’s schedule and\ncreates a lack of service for the client. It is the employee’s responsibility to find a co-worker as a\nreplacement for a scheduled shift if the employee is not able to work that shift (See Shift\nReplacement). If an employee is absent from work for more than two days, a doctor’s note is\nrequired upon return to work. Excessive absenteeism will result in termination. No call or no\nshow for a scheduled shift may result in immediate termination. o If an employee is going to be tardy or absent, it is mandatory that the employee call and\nspeak to their direct manager on duty and notify them of the occurrence at least 2 hours\nbefore their scheduled shift unless it is an instance that it is not possible for them to do so. (Accident, etc.), Employees must contact their Supervisor via direct phone call immediately. If an employee is unable to reach their Supervisor, the employee should keep calling up the\nchain of command until someone answers. o Texting a manager is not allowed when calling in. Employees must speak with their\nmanager directly. o Seminars/Meetings/ Training sessions are considered scheduled shifts. (See\nSeminar/Webinar Attendance section)",
  },
  {
    chunkIndex: 34,
    chunkId: "jba-34",
    page: 16,
    printedPage: 15,
    locator: "Page 15 — Late Opening",
    section: "Late Opening",
    sections: [
      { heading: "Late Opening", page: 15 },
      { heading: "Texting as General Work communications", page: 15 },
      { heading: "Dress Code for The Company", page: 15 },
    ],
    content: "15 | P a g e\nLate Opening\nWhen an employee assigned to open a location is unable to open the location at the proper\ntime, the employee must notify the manager a",
  },
  {
    chunkIndex: 35,
    chunkId: "jba-35",
    page: 16,
    printedPage: 15,
    locator: "Page 15 — Shoes",
    section: "Shoes",
    sections: [
      { heading: "Shoes", page: 15 },
      { heading: "Belts", page: 15 },
      { heading: "Hair", page: 15 },
    ],
    content: "Anyone\nviolating their Brand’s Dress code policy will be sent home to change into proper work attire and\nmay be subject to disciplinary action, up to and potent",
  },
  {
    chunkIndex: 36,
    chunkId: "jba-36",
    page: 17,
    printedPage: 16,
    locator: "Page 16 — Facial Hair",
    section: "Facial Hair",
    sections: [
      { heading: "Facial Hair", page: 16 },
      { heading: "Make-up", page: 16 },
      { heading: "Jewelry/Accessories", page: 16 },
      { heading: "Tattoos", page: 16 },
    ],
    content: "16 | P a g e\nFacial Hair\no Facial hair is acceptable as long as it is clean, well-groomed, and trimmed. Make-up\no Due to the nature of working in the Beauty Ind",
  },
  {
    chunkIndex: 37,
    chunkId: "jba-37",
    page: 17,
    printedPage: 16,
    locator: "Page 16",
    section: null,
    sections: [],
    content: "o Front Desk and Management’s pants must be solid khaki or black in color. o Pants must be full length and free of holes or frayed edges.\n\nBuff City Soap:\nShirt",
  },
  {
    chunkIndex: 38,
    chunkId: "jba-38",
    page: 18,
    printedPage: 17,
    locator: "Page 17 — Tanning",
    section: "Tanning",
    sections: [
      { heading: "Tanning", page: 17 },
    ],
    content: "17 | P a g e\no No patches, rips, or holes are to be noticeable on the shirt. Pants\no Full length black or blue jean-colored pants are acceptable. o Yoga pants, ",
  },
  {
    chunkIndex: 39,
    chunkId: "jba-39",
    page: 18,
    printedPage: 17,
    locator: "Page 17",
    section: null,
    sections: [],
    content: "Pants\no Full length khaki or black pants are acceptable. o Full length black or blue jean-colored pants are acceptable as long as they are free of tears\nor exce",
  },
  {
    chunkIndex: 40,
    chunkId: "jba-40",
    page: 19,
    printedPage: 18,
    locator: "Page 18 — Employee Parking",
    section: "Employee Parking",
    sections: [
      { heading: "Employee Parking", page: 18 },
      { heading: "Lost and Found", page: 18 },
    ],
    content: "18 | P a g e\nPersonal Items:\nPersonal items (books, laptops, other electronics, etc.) do not belong inside The Company,\nunless necessary. Employees are expected",
  },
  {
    chunkIndex: 41,
    chunkId: "jba-41",
    page: 19,
    printedPage: 18,
    locator: "Page 18 — Facility Repair/Service Vendors",
    section: "Facility Repair/Service Vendors",
    sections: [
      { heading: "Facility Repair/Service Vendors", page: 18 },
      { heading: "Purchasing Authorizations", page: 18 },
    ],
    content: "o If an item is found by an Employee, it is their legal responsibility to return it to the rightful\nowner. Deviations from this policy will not be tolerated.\n\nI",
  },
  {
    chunkIndex: 42,
    chunkId: "jba-42",
    page: 20,
    printedPage: 19,
    locator: "Page 19 — Discounting",
    section: "Discounting",
    sections: [
      { heading: "Discounting", page: 19 },
      { heading: "Coupon Collection", page: 19 },
    ],
    content: "19 | P a g e\nCompany, unless given prior approval in writing by Upper Management, official company\ndirective, or the legal department. Employees are prohibited ",
  },
  {
    chunkIndex: 43,
    chunkId: "jba-43",
    page: 20,
    printedPage: 19,
    locator: "Page 19 — Cell Phone/Smart Watch Policy",
    section: "Cell Phone/Smart Watch Policy",
    sections: [
      { heading: "Cell Phone/Smart Watch Policy", page: 19 },
      { heading: "Company Email Account", page: 19 },
    ],
    content: "Write the promotional offer the\ncustomer has shown using their phone on a receipt.\n\nThe receipt in turn becomes\ntheir coupon. o Write employee name, the custome",
  },
  {
    chunkIndex: 44,
    chunkId: "jba-44",
    page: 21,
    printedPage: 20,
    locator: "Page 20 — Point of Sale and Alarm Passwords",
    section: "Point of Sale and Alarm Passwords",
    sections: [
      { heading: "Point of Sale and Alarm Passwords", page: 20 },
      { heading: "Employment Verification", page: 20 },
      { heading: "Outside Employment", page: 20 },
      { heading: "Fraternization Policy", page: 20 },
    ],
    content: "20 | P a g e\nPoint of Sale and Alarm Passwords\nEmployees must always use their own personal passwords and alarm codes. Do NOT share\nalarm codes or passwords. Us",
  },
  {
    chunkIndex: 45,
    chunkId: "jba-45",
    page: 21,
    printedPage: 20,
    locator: "Page 20 — Employment and Supervision of Relatives",
    section: "Employment and Supervision of Relatives",
    sections: [
      { heading: "Employment and Supervision of Relatives", page: 20 },
      { heading: "Solicitation", page: 20 },
    ],
    content: "Anyone in a Supervisory\nposition is prohibited from dating a subordinate, without Management Team approval.\n\nPersonal\nrelationships between Employees should not",
  },
  {
    chunkIndex: 46,
    chunkId: "jba-46",
    page: 22,
    printedPage: 21,
    locator: "Page 21 — Care and Cleaning of Equipment and Facilities",
    section: "Care and Cleaning of Equipment and Facilities",
    sections: [
      { heading: "Care and Cleaning of Equipment and Facilities", page: 21 },
      { heading: "No Public Restrooms", page: 21 },
      { heading: "Location Closing Times", page: 21 },
      { heading: "Background Checks", page: 21 },
      { heading: "Business Ethics", page: 21 },
      { heading: "Communication and Confidentiality Policies", page: 21 },
      { heading: "Confidential Information Policy", page: 21 },
    ],
    content: "21 | P a g e\nworkplace, they must submit it to Management for approval. The Manager will post all\napproved messages. Care and Cleaning of Equipment and Faciliti",
  },
  {
    chunkIndex: 47,
    chunkId: "jba-47",
    page: 22,
    printedPage: 21,
    locator: "Page 21 — Communication and Confidentiality Policies",
    section: "Communication and Confidentiality Policies",
    sections: [
      { heading: "Communication and Confidentiality Policies", page: 21 },
      { heading: "Confidential Information Policy", page: 21 },
    ],
    content: "Communication and Confidentiality Policies\nConfidential Information Policy\nAll Company data and information is the property of The Company and is intended for c",
  },
  {
    chunkIndex: 48,
    chunkId: "jba-48",
    page: 23,
    printedPage: 22,
    locator: "Page 22 — Nondisclosure Agreement Policy",
    section: "Nondisclosure Agreement Policy",
    sections: [
      { heading: "Nondisclosure Agreement Policy", page: 22 },
      { heading: "Talking to the Media/Press", page: 22 },
    ],
    content: "22 | P a g e\n▪ Do not use a word or phrase of special importance to you, i.e., birthday, place, or\nvehicle. ▪ Do not use default passwords, i.e., password123. ▪",
  },
  {
    chunkIndex: 49,
    chunkId: "jba-49",
    page: 23,
    printedPage: 22,
    locator: "Page 22 — Social Media Policy",
    section: "Social Media Policy",
    sections: [
      { heading: "Social Media Policy", page: 22 },
    ],
    content: "Please direct any and all media inquiries to the\nCorporate Office.\n\nSocial Media Policy\nThe Company understands that social media can be a fun and rewarding way",
  },
  {
    chunkIndex: 50,
    chunkId: "jba-50",
    page: 24,
    printedPage: 23,
    locator: "Page 23 — Using Social Media at Work",
    section: "Using Social Media at Work",
    sections: [
      { heading: "Using Social Media at Work", page: 23 },
      { heading: "Retaliation is Prohibited", page: 23 },
    ],
    content: "23 | P a g e\nEmployees should be honest and accurate when posting information or news, if an employee\nmake a mistake, correct it quickly. Maintain the confident",
  },
  {
    chunkIndex: 51,
    chunkId: "jba-51",
    page: 24,
    printedPage: 23,
    locator: "Page 23 — Information Security and IT Overview Policy",
    section: "Information Security and IT Overview Policy",
    sections: [
      { heading: "Information Security and IT Overview Policy", page: 23 },
    ],
    content: "If\nemployees have a question or need further guidance, please contact Human Resources.\n\nInformation Security and IT Overview Policy\nCompany assets include anyth",
  },
  {
    chunkIndex: 52,
    chunkId: "jba-52",
    page: 24,
    printedPage: 23,
    locator: "Page 23",
    section: null,
    sections: [],
    content: "In addition, having an email address on the internet may\nlead to the receipt of unsolicited emails containing offensive content. Users accessing the\ninternet do",
  },
  {
    chunkIndex: 53,
    chunkId: "jba-53",
    page: 25,
    printedPage: 24,
    locator: "Page 24 — Communications Systems Policy",
    section: "Communications Systems Policy",
    sections: [
      { heading: "Communications Systems Policy", page: 24 },
    ],
    content: "24 | P a g e\nor servers. The computer systems and servers belong to The Company and may only be\nused for business purposes. o Monitoring of Computer Usage: The ",
  },
  {
    chunkIndex: 54,
    chunkId: "jba-54",
    page: 25,
    printedPage: 24,
    locator: "Page 24 — Communications Systems Policy",
    section: "Communications Systems Policy",
    sections: [
      { heading: "Communications Systems Policy", page: 24 },
      { heading: "Information Technology Support", page: 24 },
    ],
    content: "Communications Systems Policy\nTelephones, mail systems, computers, internet access, email, and etc. provided by The Company\nare company property and may be acce",
  },
  {
    chunkIndex: 55,
    chunkId: "jba-55",
    page: 26,
    printedPage: 25,
    locator: "Page 25 — Safety in the Workplace",
    section: "Safety in the Workplace",
    sections: [
      { heading: "Safety in the Workplace", page: 25 },
      { heading: "Security Policy", page: 25 },
      { heading: "Statement of Safety in the Workplace Policy", page: 25 },
    ],
    content: "25 | P a g e\no All other: HelpDesk@buffcitysoap.com\nCrunch Fitness:\no Phone: 1-888-622-6290\no Email: myabcid@abcfinancial.com\no Woven Support Email: support@wov",
  },
  {
    chunkIndex: 56,
    chunkId: "jba-56",
    page: 26,
    printedPage: 25,
    locator: "Page 25",
    section: null,
    sections: [],
    content: "The success of The Company will depend not only on production and sales, but also how safely\neach job is performed.\n\nThere is neither a job so important nor any",
  },
  {
    chunkIndex: 57,
    chunkId: "jba-57",
    page: 27,
    printedPage: 26,
    locator: "Page 26 — Emergency Situation Notification Requirement",
    section: "Emergency Situation Notification Requirement",
    sections: [
      { heading: "Emergency Situation Notification Requirement", page: 26 },
    ],
    content: "26 | P a g e\nto company records of work-related injuries and illnesses, subject to certain limitations imposed\nby 29 CFR 1904.35(b)(2). To report a work-related",
  },
  {
    chunkIndex: 58,
    chunkId: "jba-58",
    page: 27,
    printedPage: 26,
    locator: "Page 26 — Incident Reporting",
    section: "Incident Reporting",
    sections: [
      { heading: "Incident Reporting", page: 26 },
    ],
    content: "When operations are officially closed due to emergency conditions, per\nFLSA requirements, time off from scheduled work will be paid for all salary exempt Employ",
  },
  {
    chunkIndex: 59,
    chunkId: "jba-59",
    page: 28,
    printedPage: 27,
    locator: "Page 27 — Employee Non-Work-Related Injury/Illness Accommodations",
    section: "Employee Non-Work-Related Injury/Illness Accommodations",
    sections: [
      { heading: "Employee Non-Work-Related Injury/Illness Accommodations", page: 27 },
    ],
    content: "27 | P a g e\nFollowing any work-related injury or illness, regardless of severity, it is the Employee’s\nresponsibility to report the injury/illness immediately ",
  },
  {
    chunkIndex: 60,
    chunkId: "jba-60",
    page: 28,
    printedPage: 27,
    locator: "Page 27 — Employee Non-Work-Related Injury/Illness Accommodations",
    section: "Employee Non-Work-Related Injury/Illness Accommodations",
    sections: [
      { heading: "Employee Non-Work-Related Injury/Illness Accommodations", page: 27 },
      { heading: "Problem Resolution", page: 27 },
    ],
    content: "Employee Non-Work-Related Injury/Illness Accommodations\nWhen a potential new hire or current Employee is stating they have work restrictions or when\nThe Company",
  },
  {
    chunkIndex: 61,
    chunkId: "jba-61",
    page: 28,
    printedPage: 27,
    locator: "Page 27",
    section: null,
    sections: [],
    content: "The Employee may discontinue the procedure at any step.\n\no An Employee presents a problem to their immediate Supervisor within 7 calendar days, or\nas soon as re",
  },
  {
    chunkIndex: 62,
    chunkId: "jba-62",
    page: 29,
    printedPage: 28,
    locator: "Page 28 — Workplace Violence Prevention",
    section: "Workplace Violence Prevention",
    sections: [
      { heading: "Workplace Violence Prevention", page: 28 },
    ],
    content: "28 | P a g e\no The Supervisor responds to the problem during a discussion or within 7 calendar days, or as\nsoon as reasonably possible after consulting with app",
  },
  {
    chunkIndex: 63,
    chunkId: "jba-63",
    page: 29,
    printedPage: 28,
    locator: "Page 28",
    section: null,
    sections: [],
    content: "Employees are expected to refrain from fighting, “horseplay”, or other\nconduct that may be dangerous to others.\n\nFirearms, weapons, and other dangerous or\nhazar",
  },
  {
    chunkIndex: 64,
    chunkId: "jba-64",
    page: 30,
    printedPage: 29,
    locator: "Page 29 — Visitors in the Workplace",
    section: "Visitors in the Workplace",
    sections: [
      { heading: "Visitors in the Workplace", page: 29 },
    ],
    content: "29 | P a g e\nAnyone determined to be responsible for threats of (or actual) violence or other conduct that is\nin violation of these guidelines will be subject t",
  },
  {
    chunkIndex: 65,
    chunkId: "jba-65",
    page: 30,
    printedPage: 29,
    locator: "Page 29",
    section: null,
    sections: [],
    content: "If the Employee is uncomfortable with allowing the visitor into the\nworkplace, the Supervisor or manager on duty must refuse to allow the visitor into the\nworkp",
  },
  {
    chunkIndex: 66,
    chunkId: "jba-66",
    page: 30,
    printedPage: 29,
    locator: "Page 29",
    section: null,
    sections: [],
    content: "Do not try to intercede. The Company will promptly and thoroughly\ninvestigate all reports of threats of (or actual) violence and of suspicious individuals or ac",
  },
  {
    chunkIndex: 67,
    chunkId: "jba-67",
    page: 31,
    printedPage: 30,
    locator: "Page 30 — Animals in the Workplace",
    section: "Animals in the Workplace",
    sections: [
      { heading: "Animals in the Workplace", page: 30 },
      { heading: "Robberies", page: 30 },
    ],
    content: "30 | P a g e\nAnimals in the Workplace\nThe Company is responsible for assuring the health and safety of all Employees in the\nworkplace. While we understand that ",
  },
  {
    chunkIndex: 68,
    chunkId: "jba-68",
    page: 31,
    printedPage: 30,
    locator: "Page 30 — Handling Theft",
    section: "Handling Theft",
    sections: [
      { heading: "Handling Theft", page: 30 },
    ],
    content: "Do not in anyway attempt to foil the\nrobbery, negotiate, or battle wits with a potential robber(s).\n\nThe safety of our Employees, outside vendors, guests, and r",
  },
  {
    chunkIndex: 69,
    chunkId: "jba-69",
    page: 32,
    printedPage: 31,
    locator: "Page 31 — Proper Use of General Operating Equipment",
    section: "Proper Use of General Operating Equipment",
    sections: [
      { heading: "Proper Use of General Operating Equipment", page: 31 },
      { heading: "Wet Floor Sign", page: 31 },
      { heading: "Portable Fire Extinguisher & Fire Prevention Plan", page: 31 },
    ],
    content: "31 | P a g e\nProper Use of General Operating Equipment\nEmployees will be required to use items such as ladders, carts, stools, etc. to perform daily tasks\nsuch ",
  },
  {
    chunkIndex: 70,
    chunkId: "jba-70",
    page: 32,
    printedPage: 31,
    locator: "Page 31 — Vehicle Fleet Usage Policy and Guidelines",
    section: "Vehicle Fleet Usage Policy and Guidelines",
    sections: [
      { heading: "Vehicle Fleet Usage Policy and Guidelines", page: 31 },
    ],
    content: "o Training will also be repeated annually. Employees who are not trained to use fire extinguishers are advised that their only duties in a\nfire are responsible ",
  },
  {
    chunkIndex: 71,
    chunkId: "jba-71",
    page: 33,
    printedPage: 32,
    locator: "Page 32 — Driver Safety Rules",
    section: "Driver Safety Rules",
    sections: [
      { heading: "Driver Safety Rules", page: 32 },
    ],
    content: "32 | P a g e\nduring the operation of a company vehicle, or while driving a personal vehicle on company\nbusiness, within 72 hours to Human Resources. A driving r",
  },
  {
    chunkIndex: 72,
    chunkId: "jba-72",
    page: 33,
    printedPage: 32,
    locator: "Page 32 — Accident Procedures",
    section: "Accident Procedures",
    sections: [
      { heading: "Accident Procedures", page: 32 },
    ],
    content: "Cell phone use while driving should be kept to a minimum and\nwhen done shall only be done in a manner that does not distract the driver.\n\nDrivers are responsibl",
  },
  {
    chunkIndex: 73,
    chunkId: "jba-73",
    page: 34,
    printedPage: 33,
    locator: "Page 33 — Employment Status & Records",
    section: "Employment Status & Records",
    sections: [
      { heading: "Employment Status & Records", page: 33 },
      { heading: "Employee Classifications", page: 33 },
    ],
    content: "33 | P a g e\nformal accident review conducted on each accident to determine cause and how the accident\ncould have been prevented. Employment Status & Records\nEm",
  },
  {
    chunkIndex: 74,
    chunkId: "jba-74",
    page: 34,
    printedPage: 33,
    locator: "Page 33 — Orientation",
    section: "Orientation",
    sections: [
      { heading: "Orientation", page: 33 },
      { heading: "Introductory Period (Probationary Period)", page: 33 },
    ],
    content: "o Exempt – All exempt Employees are paid on a bi-weekly salary basis. Hours worked by\nsalaried Employees can be irregular.\n\nSalaried Employees are exempt from t",
  },
  {
    chunkIndex: 75,
    chunkId: "jba-75",
    page: 35,
    printedPage: 34,
    locator: "Page 34 — Evaluations and Raises",
    section: "Evaluations and Raises",
    sections: [
      { heading: "Evaluations and Raises", page: 34 },
    ],
    content: "34 | P a g e\ncapabilities, work habits, and overall performance. Either the Employee or The Company may\nend the employment relationship at will, at any time, du",
  },
  {
    chunkIndex: 76,
    chunkId: "jba-76",
    page: 35,
    printedPage: 34,
    locator: "Page 34 — Promotions",
    section: "Promotions",
    sections: [
      { heading: "Promotions", page: 34 },
      { heading: "What to Expect When Terminated", page: 34 },
      { heading: "Employment Termination", page: 34 },
    ],
    content: "The Company cannot\npromise or guarantee that raises will occur as raises are based upon several factors including but\nnot limited to: Employee performance, loca",
  },
  {
    chunkIndex: 77,
    chunkId: "jba-77",
    page: 36,
    printedPage: 35,
    locator: "Page 35 — Return of Property",
    section: "Return of Property",
    sections: [
      { heading: "Return of Property", page: 35 },
      { heading: "Pay on Separation of Employment", page: 35 },
    ],
    content: "35 | P a g e\nReturn of Property\nEmployees must return all company property immediately upon request and no later than 5 pm\nthe following business day upon termi",
  },
  {
    chunkIndex: 78,
    chunkId: "jba-78",
    page: 36,
    printedPage: 35,
    locator: "Page 35 — Employee Records",
    section: "Employee Records",
    sections: [
      { heading: "Employee Records", page: 35 },
    ],
    content: "A two (2) week notice is required for all full time and part-time Employees, and a thirty (30) day\nnotice is required for all Management positions.\n\nIf employee",
  },
  {
    chunkIndex: 79,
    chunkId: "jba-79",
    page: 37,
    printedPage: 36,
    locator: "Page 36 — Liquidating 401K",
    section: "Liquidating 401K",
    sections: [
      { heading: "Liquidating 401K", page: 36 },
      { heading: "Accessing W-2’s", page: 36 },
    ],
    content: "36 | P a g e\nChanges must be communicated/updated within 30 days of the information change taking\neffect. Former Employees do not have access to their files oth",
  },
  {
    chunkIndex: 80,
    chunkId: "jba-80",
    page: 37,
    printedPage: 36,
    locator: "Page 36 — Timekeeping & Payroll",
    section: "Timekeeping & Payroll",
    sections: [
      { heading: "Timekeeping & Payroll", page: 36 },
      { heading: "Time Records", page: 36 },
    ],
    content: "o Print your W-2’s directly from the Paycor system. o If you Change your address you need to notify your payroll department.\n\nTimekeeping & Payroll\nTime Records",
  },
  {
    chunkIndex: 81,
    chunkId: "jba-81",
    page: 38,
    printedPage: 37,
    locator: "Page 37 — Schedule Requests/General availability Changes",
    section: "Schedule Requests/General availability Changes",
    sections: [
      { heading: "Schedule Requests/General availability Changes", page: 37 },
      { heading: "Shift Replacement", page: 37 },
    ],
    content: "37 | P a g e\nworked as reported to Payroll by their direct Supervisor and sign off to confirm their accuracy. Any discrepancies should be reported to your direc",
  },
  {
    chunkIndex: 82,
    chunkId: "jba-82",
    page: 38,
    printedPage: 37,
    locator: "Page 37 — Shift Replacement",
    section: "Shift Replacement",
    sections: [
      { heading: "Shift Replacement", page: 37 },
      { heading: "Seminar/Webinar Attendance", page: 37 },
    ],
    content: "Shift Replacement\nShift trading between employees disrupts company operations and is generally discouraged.\n\nHowever, in emergency situations, employees may trade shifts with prior approval from\nmanagement. It is the responsibility of the employee to find a replacement for their shift. If an\nemployee is unable to work due to illness, emergency, or unforeseen circumstances, they must\nimmediately call and speak directly with their supervisor to notify them of the situation. Employees should provide at least two hours’ notice when calling in as a courtesy to colleagues. In the event of an emergency where two hours’ notice is not possible the employee must\ncontact their supervisor directly by phone immediately. Texting is NOT an acceptable method of\ncommunication a phone call is required. Seminar/Webinar Attendance\nIf you are enrolled in a seminar/webinar and do not attend the seminar without notifying your\nSupervisor, it is considered a no call no show to a scheduled shift. If you cannot attend a\nseminar/webinar you are scheduled for, you must notify your Supervisor via a personal phone\ncall. Notice of a call-in should not occur “last minute” and should be completed at least two (2)\nhours in advance out of courtesy to fellow Employees. In cases of emergency where two (2)\nhours advance notice is not possible (accident, etc.), you must contact your Supervisor via direct\nphone call immediately.",
  },
  {
    chunkIndex: 83,
    chunkId: "jba-83",
    page: 39,
    printedPage: 38,
    locator: "Page 38 — Meal and Rest Policy",
    section: "Meal and Rest Policy",
    sections: [
      { heading: "Meal and Rest Policy", page: 38 },
      { heading: "Overtime", page: 38 },
    ],
    content: "38 | P a g e\nMeal and Rest Policy\nDuring your employment with The Company, you will be expected to take meal and rest period\nbreaks in accordance with this poli",
  },
  {
    chunkIndex: 84,
    chunkId: "jba-84",
    page: 39,
    printedPage: 38,
    locator: "Page 38 — Pay Periods",
    section: "Pay Periods",
    sections: [
      { heading: "Pay Periods", page: 38 },
      { heading: "Bonus Policy", page: 38 },
    ],
    content: "This is in accordance with federal and state wage\nand hour restrictions. Overtime pay is based on actual hours worked.\n\nTime off on vacation leave,\nholidays, or",
  },
  {
    chunkIndex: 85,
    chunkId: "jba-85",
    page: 40,
    printedPage: 39,
    locator: "Page 39 — Payroll Deductions",
    section: "Payroll Deductions",
    sections: [
      { heading: "Payroll Deductions", page: 39 },
      { heading: "Garnishment of Employee Wages", page: 39 },
      { heading: "Overnight Travel Reimbursement", page: 39 },
    ],
    content: "39 | P a g e\none day’s notice. Please see your Supervisor regarding brand’s bonus policies and incentive pay\nprograms to find those that apply to your specific ",
  },
  {
    chunkIndex: 86,
    chunkId: "jba-86",
    page: 40,
    printedPage: 39,
    locator: "Page 39 — Overnight Travel Reimbursement",
    section: "Overnight Travel Reimbursement",
    sections: [
      { heading: "Overnight Travel Reimbursement", page: 39 },
    ],
    content: "Overnight Travel Reimbursement\nTravel time/expense reimbursements for work requiring overnight stays away from your home\ncommunity include:\no Reimbursements for",
  },
  {
    chunkIndex: 87,
    chunkId: "jba-87",
    page: 41,
    printedPage: 40,
    locator: "Page 40 — Error in Pay",
    section: "Error in Pay",
    sections: [
      { heading: "Error in Pay", page: 40 },
      { heading: "Fair Labor Standard Act (FSLA) – Safe Harbor Policy", page: 40 },
    ],
    content: "40 | P a g e\nspouse or companion(s) is considered personal and no portion of the expense is\nreimbursable, including the Employee’s portion. Error in Pay\nAll Emp",
  },
  {
    chunkIndex: 88,
    chunkId: "jba-88",
    page: 41,
    printedPage: 40,
    locator: "Page 40",
    section: null,
    sections: [],
    content: "o Exempt (salaried) Employees do not need to be paid for any work week in which they\nperform no work and will not be paid unless appropriate accrued paid leave ",
  },
  {
    chunkIndex: 89,
    chunkId: "jba-89",
    page: 42,
    printedPage: 41,
    locator: "Page 41 — Salary Administration",
    section: "Salary Administration",
    sections: [
      { heading: "Salary Administration", page: 41 },
    ],
    content: "41 | P a g e\npartial-day or full-day absences due to illness, injury, or personal reasons when accrued paid\nleave is not used by an Employee because:\no The Empl",
  },
  {
    chunkIndex: 90,
    chunkId: "jba-90",
    page: 42,
    printedPage: 41,
    locator: "Page 41 — Salary Administration",
    section: "Salary Administration",
    sections: [
      { heading: "Salary Administration", page: 41 },
      { heading: "Employee Benefits", page: 41 },
      { heading: "Paid time Off (PTO)", page: 41 },
    ],
    content: "Salary Administration\nThe salary administration program at The Company was created to achieve consistent pay\npractices, comply with federal and state laws, mirr",
  },
  {
    chunkIndex: 91,
    chunkId: "jba-91",
    page: 43,
    printedPage: 42,
    locator: "Page 42 — Holiday Benefits",
    section: "Holiday Benefits",
    sections: [
      { heading: "Holiday Benefits", page: 42 },
    ],
    content: "42 | P a g e\no 5-9 years of service in a full-time position – 3 weeks (120 hours), with a maximum accrual\ncap of 160 hours. o 10+ years of service in a full-tim",
  },
  {
    chunkIndex: 92,
    chunkId: "jba-92",
    page: 43,
    printedPage: 42,
    locator: "Page 42 — Holiday Benefits",
    section: "Holiday Benefits",
    sections: [
      { heading: "Holiday Benefits", page: 42 },
    ],
    content: "Holiday Benefits\nEach FT salaried manager and FT corporate staff member will receive 8 hours of pay for each\nholiday.\n\nCorporate Office:\nThe Corporate Office is",
  },
  {
    chunkIndex: 93,
    chunkId: "jba-93",
    page: 44,
    printedPage: 43,
    locator: "Page 43 — Employee Discounts for Company Products and Services",
    section: "Employee Discounts for Company Products and Services",
    sections: [
      { heading: "Employee Discounts for Company Products and Services", page: 43 },
    ],
    content: "43 | P a g e\no New Years Day\no Independence Day\no Thanksgiving Day\no Christmas Day\no Easter\nThe salons will be open on Memorial Day. Crunch Fitness:\nCrunch Fitn",
  },
  {
    chunkIndex: 94,
    chunkId: "jba-94",
    page: 44,
    printedPage: 43,
    locator: "Page 43",
    section: null,
    sections: [],
    content: "o Buff City Soap: 50% off products, 25% off bath bomb parties. o Crunch Fitness: 50% off an all access gym membership, 50% off products.\n\nPlease keep in mind th",
  },
  {
    chunkIndex: 95,
    chunkId: "jba-95",
    page: 45,
    printedPage: 44,
    locator: "Page 44 — Buddy Passes (Sun Tan City Employees ONLY)",
    section: "Buddy Passes (Sun Tan City Employees ONLY)",
    sections: [
      { heading: "Buddy Passes (Sun Tan City Employees ONLY)", page: 44 },
    ],
    content: "44 | P a g e\no No tanning while on the clock. o Another employee is required to process each employee tanning session; employees will not\nbe able to tan without",
  },
  {
    chunkIndex: 96,
    chunkId: "jba-96",
    page: 45,
    printedPage: 44,
    locator: "Page 44 — Employee Insurance Benefits",
    section: "Employee Insurance Benefits",
    sections: [
      { heading: "Employee Insurance Benefits", page: 44 },
    ],
    content: "Any employee who is involuntarily terminated or who does\nnot leave in good standing, will be required to relinquish all unused Buddy Passes to their Salon\nDirec",
  },
  {
    chunkIndex: 97,
    chunkId: "jba-97",
    page: 46,
    printedPage: 45,
    locator: "Page 45 — HIPAA",
    section: "HIPAA",
    sections: [
      { heading: "HIPAA", page: 45 },
      { heading: "Group Health Plan Continuation Coverage Under COBRA", page: 45 },
    ],
    content: "45 | P a g e\n▪ Employer Paid Life – The Company provides full-time Employees with\n$20,000 of group life insurance. o Plan Details:\no Eligible Employees may find",
  },
  {
    chunkIndex: 98,
    chunkId: "jba-98",
    page: 46,
    printedPage: 45,
    locator: "Page 45",
    section: null,
    sections: [],
    content: "COBRA continuation coverage only lasts for a limited period of time.\n\nThe Company provides each covered Employee and spouse (if any) with written notice\nexplain",
  },
  {
    chunkIndex: 99,
    chunkId: "jba-99",
    page: 47,
    printedPage: 46,
    locator: "Page 46 — Leave Requests",
    section: "Leave Requests",
    sections: [
      { heading: "Leave Requests", page: 46 },
      { heading: "Family Medical Leave", page: 46 },
    ],
    content: "46 | P a g e\nLeave Requests\nFamily Medical Leave\nThe Company provides family leaves of absence without pay to eligible Employees who wish to\ntake time off from ",
  },
  {
    chunkIndex: 100,
    chunkId: "jba-100",
    page: 47,
    printedPage: 46,
    locator: "Page 46 — Bereavement Leave",
    section: "Bereavement Leave",
    sections: [
      { heading: "Bereavement Leave", page: 46 },
    ],
    content: "If this initial period of absence proves insufficient, consideration will be given to a written\nrequest for a single extension of no more than 30 calendar days.",
  },
  {
    chunkIndex: 101,
    chunkId: "jba-101",
    page: 47,
    printedPage: 46,
    locator: "Page 46",
    section: null,
    sections: [],
    content: "These should be submitted at the time of\nrequest or upon return from leave.\n\nAs an alternative to this documentation, you may provide\nthe name of the deceased, ",
  },
  {
    chunkIndex: 102,
    chunkId: "jba-102",
    page: 48,
    printedPage: 47,
    locator: "Page 47 — Military Leave",
    section: "Military Leave",
    sections: [
      { heading: "Military Leave", page: 47 },
      { heading: "Time Off to Vote or Serve as an Election Officer", page: 47 },
    ],
    content: "47 | P a g e\nAfter receiving the approved request, the Human Resources Department will submit the\nBereavement days in your personnel profile under the PTO secti",
  },
  {
    chunkIndex: 103,
    chunkId: "jba-103",
    page: 48,
    printedPage: 47,
    locator: "Page 47 — Jury Duty",
    section: "Jury Duty",
    sections: [
      { heading: "Jury Duty", page: 47 },
      { heading: "Witness Duty", page: 47 },
    ],
    content: "Advance notice is required so that the necessary time off\ncan be scheduled at the beginning or end of the work shift, whichever provides the least\ndisruption to",
  },
  {
    chunkIndex: 104,
    chunkId: "jba-104",
    page: 49,
    printedPage: 48,
    locator: "Page 48 — Maternity Leave",
    section: "Maternity Leave",
    sections: [
      { heading: "Maternity Leave", page: 48 },
    ],
    content: "48 | P a g e\nEmployees must show the witness duty summons to their Supervisor as soon as possible so the\nSupervisor may make arrangements to schedules to accomm",
  },
  {
    chunkIndex: 105,
    chunkId: "jba-105",
    page: 49,
    printedPage: 48,
    locator: "Page 48 — Client Tanning Policies and Regulations (STC & Crunch ONLY)",
    section: "Client Tanning Policies and Regulations (STC & Crunch ONLY)",
    sections: [
      { heading: "Client Tanning Policies and Regulations (STC & Crunch ONLY)", page: 48 },
      { heading: "Protecting the Client from Overexposing", page: 48 },
    ],
    content: "The Department of Labor website\nis: http://www.dol.gov/esa/regs/statutes/whd/fmla.htm#content\nIf an employee wishes to take any leave, a Leave Request Form must",
  },
  {
    chunkIndex: 106,
    chunkId: "jba-106",
    page: 50,
    printedPage: 49,
    locator: "Page 49 — Consent Forms (New Client Release Forms)",
    section: "Consent Forms (New Client Release Forms)",
    sections: [
      { heading: "Consent Forms (New Client Release Forms)", page: 49 },
      { heading: "Eye Protection", page: 49 },
      { heading: "VersaSpa® Recommendations", page: 49 },
    ],
    content: "49 | P a g e\nin one day. Likewise, if a client tells you that he/she has tanned elsewhere the same day or been\nin the sun all day; you may not tan them. Consent",
  },
  {
    chunkIndex: 107,
    chunkId: "jba-107",
    page: 50,
    printedPage: 49,
    locator: "Page 49 — Tanning While Pregnant",
    section: "Tanning While Pregnant",
    sections: [
      { heading: "Tanning While Pregnant", page: 49 },
      { heading: "Tanning with Skin Cancer", page: 49 },
      { heading: "Minors", page: 49 },
      { heading: "Children Left Unattended", page: 49 },
    ],
    content: "It is not required that clients use the FDA recommended protection during their sunless\nsessions; however, we want to educate the client’s on the items they hav",
  },
  {
    chunkIndex: 108,
    chunkId: "jba-108",
    page: 51,
    printedPage: 50,
    locator: "Page 50 — One Tanner per Room",
    section: "One Tanner per Room",
    sections: [
      { heading: "One Tanner per Room", page: 50 },
      { heading: "Employee Acknowledgement", page: 50 },
    ],
    content: "50 | P a g e\nOne Tanner per Room\nThere is only one client allowed per tanning room. Equipment should not be activated if there is\nmore than one person in the ta",
  },
  {
    chunkIndex: 109,
    chunkId: "jba-109",
    page: 51,
    printedPage: 50,
    locator: "Page 50",
    section: null,
    sections: [],
    content: "I understand\nthat if I request a copy of this employee manual, it will be provided to me. Otherwise, a copy is available\nfor my review at my work location.\n\nFur",
  },
];
