import { isDemoMode } from "@/lib/config/runtime";
import { ClaudeProvider } from "./claude-provider";
import { MockAIProvider } from "./mock-provider";
import type { AIProvider } from "./types";

export * from "./types";
export { MockAIProvider } from "./mock-provider";
export { ClaudeProvider } from "./claude-provider";
export { AiError } from "./errors";

/**
 * AI PROVIDER SELECTION — centralized, mode-aware, and one-way.
 *
 * demo -> MockAIProvider: seeded answer bank, no network, no key. This is what
 *         lets the prototype run with nothing configured.
 *
 * live -> ClaudeProvider: posts to /api/chat, which retrieves company knowledge
 *         and calls Claude server-side.
 *
 * THE RULE THIS FUNCTION EXISTS TO ENFORCE: live mode never degrades into demo
 * mode. There is no try/catch here that swaps one provider for the other. A
 * manager acting on a fabricated policy because a service was down is the
 * failure this codebase is built to make impossible — so a live-mode failure
 * surfaces as an error, every time.
 */
let cached: AIProvider | null = null;

export function getAIProvider(): AIProvider {
  cached ??= isDemoMode() ? new MockAIProvider() : new ClaudeProvider();
  return cached;
}

/** Honest label for the UI — never claims a connection that does not exist. */
export function aiProviderStatus() {
  const provider = getAIProvider();
  return {
    name: provider.connected ? "Claude (Anthropic)" : "Demo responses",
    connected: provider.connected,
    detail: provider.connected
      ? "Answers are generated by Claude from indexed company documents."
      : "Answers come from a seeded demo knowledge base. Claude is not connected in demo mode.",
  };
}

/** Test seam — resets the singleton between cases. */
export function __resetAIProvider(): void {
  cached = null;
}
