import { extractText, getDocumentProxy } from "unpdf";
import { describe, expect, it } from "vitest";

import {
  parseFormDocument,
  renderDocument,
  type FormDocument,
  type FormVariant,
} from "./document";
import { TEMPLATE_SEEDS, DMIT_VARIANTS } from "./library";
import {
  asciiOnly,
  documentTitle,
  pdfFileName,
  renderFormPdf,
  textWidth,
  wrapText,
  type RenderMeta,
} from "./pdf-render";
import { PAGE, SIZE, pageLayout } from "./paper";

/**
 * THE PRINTED FORM, READ BACK OUT OF THE PDF IT PRODUCED.
 *
 * Every assertion here parses the generated bytes with the same library the
 * uploader uses, so what is being checked is the actual document a manager
 * downloads — not the intention of the code that drew it.
 *
 * The two that matter most are negative: no editor furniture on the page, and
 * nothing on a signature line. Those are the ways a form stops being a usable
 * business record.
 */

const seed = (key: string) => {
  const found = TEMPLATE_SEEDS.find((entry) => entry.key === key);
  if (!found) throw new Error(`no seed ${key}`);
  return found;
};

const META: RenderMeta = {
  templateName: "Coaching Form",
  templateVersion: 1,
  employeeName: "Jordan Vance",
  formDate: "2026-09-04",
  locationName: "Invented Store Alpha",
  reference: "form-0001",
  status: "finalized",
};

async function readBack(bytes: Uint8Array) {
  const pdf = await getDocumentProxy(bytes);
  const { text, totalPages } = await extractText(pdf, { mergePages: true });
  return { text, totalPages };
}

describe("a rendered coaching form", () => {
  const document = parseFormDocument(seed("coaching").document);
  const values = {
    values: {
      employee_name: "Jordan Vance",
      form_date: "2026-09-04",
      job_title: "Tanning Consultant",
      location: "Invented Store Alpha",
      coaching_details:
        "Observed three tours where the membership options were not offered. Agreed to shadow two tours daily this week.",
      other_topic: "",
    },
    checked: {
      coaching_type: ["underperformance"],
      coaching_topics: ["store_tours", "engaging_conversation"],
    },
  };

  it("is a readable PDF", async () => {
    const bytes = renderFormPdf(document, null, values, META);
    expect(new TextDecoder().decode(bytes.subarray(0, 8))).toContain("%PDF-");
    const { totalPages } = await readBack(bytes);
    expect(totalPages).toBeGreaterThanOrEqual(1);
  });

  it("prints the corporate document, not the editor", async () => {
    const bytes = renderFormPdf(document, null, values, META);
    const { text } = await readBack(bytes);

    // The document itself. The Coaching Form's masthead is title case, which
    // is how its version stores it.
    expect(text).toContain("Sun Tan City");
    expect(text).toContain("Coaching Form");
    expect(text).toContain("Employee Information");
    expect(text).toContain("Type of Coaching");
    expect(text).toContain("Jordan Vance");
    expect(text).toContain("membership options were not offered");

    // THE EDITOR'S FURNITURE MUST NOT BE THERE. These are the chips and copy an
    // administrator sees on screen; on a signed HR record they would be noise
    // at best and misleading at worst.
    for (const forbidden of [
      "AI FILLS",
      "FILLED BY HAND",
      "Ask Sunny fills",
      "Edit template",
      "STANDARD FORM",
      "All templates",
      "Select text to format",
      "Replace (PDF or Word)",
    ]) {
      expect(text, `"${forbidden}" leaked onto the page`).not.toContain(forbidden);
    }
  });

  it("marks the ticked boxes and leaves the others empty", async () => {
    const bytes = renderFormPdf(document, null, values, META);
    const { text } = await readBack(bytes);
    // Every option prints, ticked or not — a checkbox list with the unticked
    // options removed is not the same form.
    expect(text).toContain("Underperformance");
    expect(text).toContain("Retraining");
    expect(text).toContain("Store Tours");
    expect(text).toContain("New Client Documents");
  });

  it("leaves the signature lines blank, with nothing to fill them", async () => {
    const bytes = renderFormPdf(document, null, values, META);
    const { text } = await readBack(bytes);
    expect(text).toContain("Employee Signature");
    expect(text).toContain("Supervisor Signature");
    // The captions are there; the employee's name never appears ON one, because
    // a signature block carries no field key at all.
    expect(text).not.toContain("Jordan Vance Employee Signature");
  });

  it("footers every page with the template version and the page count", async () => {
    const bytes = renderFormPdf(document, null, values, META);
    const { text } = await readBack(bytes);
    expect(text).toContain("Template v1");
    expect(text).toMatch(/Page 1 of \d/);
  });

  it("says DRAFT on a draft and not on a finalized form", async () => {
    const draft = renderFormPdf(document, null, values, { ...META, status: "draft" });
    const finalized = renderFormPdf(document, null, values, META);
    expect((await readBack(draft)).text).toContain("DRAFT");
    expect((await readBack(finalized)).text).not.toContain("DRAFT");
  });
});

describe("the six-page DMIT EPP", () => {
  const document = parseFormDocument(seed("dmit-epp-tsd").document);

  it("prints the reviewed position for the chosen variant, and only that one", async () => {
    const tsd = renderFormPdf(
      document,
      DMIT_VARIANTS[0],
      { values: {}, checked: {} },
      { ...META, templateName: "DMIT EPP — TSD Review" },
    );
    const { text } = await readBack(tsd);

    expect(text).toContain("District Manager");
    // The DMIT reading's own description must not appear on a TSD review.
    expect(text).not.toContain("District Manager in Training is learning");
  });

  it("resolves every role placeholder", async () => {
    const bytes = renderFormPdf(document, DMIT_VARIANTS[1], { values: {}, checked: {} }, META);
    const { text } = await readBack(bytes);
    expect(text).not.toContain("{{role}}");
    expect(text).not.toContain("{{roleAbbr}}");
  });

  it("keeps its explicit page breaks and reaches the re-evaluation", async () => {
    const bytes = renderFormPdf(document, DMIT_VARIANTS[0], { values: {}, checked: {} }, META);
    const { text, totalPages } = await readBack(bytes);
    expect(totalPages).toBeGreaterThanOrEqual(3);
    expect(text).toContain("Follow-up");
    expect(text).toContain("Re-Evaluation");
    // Both acknowledgements, because the second one belongs to the
    // re-evaluation and losing it would lose the record of that meeting.
    expect(text.match(/Acknowledgement/g)?.length ?? 0).toBeGreaterThanOrEqual(2);
  });

  it("prints the hand-filled section as empty ruled lines", async () => {
    const bytes = renderFormPdf(document, DMIT_VARIANTS[0], { values: {}, checked: {} }, META);
    const { text } = await readBack(bytes);
    expect(text).toContain("What are your overall top three strengths?");
    expect(text).toContain("This section is completed by hand");
  });
});

/**
 * EVERY LINE OF TYPE, MEASURED AGAINST THE PAPER IT IS DRAWN ON.
 *
 * The bug this guards was reported off a printed DPOA: the last words of a
 * wrapped sentence sat past the end of the ruled line, and on the longer
 * paragraphs past the right margin of the page. It was invisible to every test
 * here, because a PDF text extractor returns the words whether or not they are
 * on the paper — the only way to see it is to add up the advance widths of a
 * drawn string and compare the result to the margin.
 *
 * So this reads the content stream rather than the text: every `Tj` on every
 * page, positioned and measured in its own face.
 */
interface DrawnLine {
  page: number;
  x: number;
  y: number;
  size: number;
  font: "regular" | "bold";
  text: string;
}

function drawnLines(bytes: Uint8Array): DrawnLine[] {
  const source = Buffer.from(bytes).toString("latin1");
  const found: DrawnLine[] = [];
  const streams = source.split("stream\n").slice(1);
  streams.forEach((chunk, page) => {
    const body = chunk.split("\nendstream")[0];
    const pattern =
      /BT [\d.]+ [\d.]+ [\d.]+ rg \/(F1|F2) ([\d.]+) Tf 1 0 0 1 ([-\d.]+) ([-\d.]+) Tm \((.*?)\) Tj ET/g;
    let match: RegExpExecArray | null;
    while ((match = pattern.exec(body))) {
      const [, resource, size, x, y, text] = match;
      found.push({
        page,
        x: Number(x),
        y: Number(y),
        size: Number(size),
        font: resource === "F2" ? "bold" : "regular",
        text,
      });
    }
  });
  return found;
}

const right = (line: DrawnLine) => line.x + textWidth(line.text, line.size, line.font);

/**
 * Every horizontal rule on the page.
 *
 * Horizontal only: the diagonal pair that ticks a checkbox uses the same
 * operator and is not a rule.
 */
interface DrawnRule {
  page: number;
  y: number;
  from: number;
  to: number;
}

function drawnRules(bytes: Uint8Array): DrawnRule[] {
  const source = Buffer.from(bytes).toString("latin1");
  const found: DrawnRule[] = [];
  source.split("stream\n").slice(1).forEach((chunk, page) => {
    const body = chunk.split("\nendstream")[0];
    const pattern = /([-\d.]+) ([-\d.]+) m ([-\d.]+) ([-\d.]+) l/g;
    let match: RegExpExecArray | null;
    while ((match = pattern.exec(body))) {
      const y1 = Number(match[2]);
      const y2 = Number(match[4]);
      if (y1 !== y2) continue;
      const x1 = Number(match[1]);
      const x2 = Number(match[3]);
      found.push({ page, y: y1, from: Math.min(x1, x2), to: Math.max(x1, x2) });
    }
  });
  return found;
}

/*
 * Glyph extremes as a fraction of the type size, from the Helvetica and
 * Helvetica-Bold bounding boxes: `g`, `y` and `j` reach 0.218em below the
 * baseline and `f` reaches 0.728em above it.
 *
 * Plus the white a reader needs to see a rule as UNDER the word. Bare
 * non-overlap is not the bar — the old 3pt rule never touched the tail of a
 * `g`, it sat 0.82pt off it, and still read as a strike-through. Below the
 * words the rule wants a clear point and a bit; above them, where it belongs
 * to the line before, crowding is all that has to be ruled out.
 */
const DESCENDER = 0.218;
const ASCENDER = 0.728;
const CLEAR_BELOW = 1.2;
const CLEAR_ABOVE = 0.6;

/** A value long enough to wrap several times in every column on every form. */
const LONG_ANSWER =
  "Employees are expected to be in appropriate, professional salon attire that " +
  "meets dress code standards for the entire scheduled shift, including any time " +
  "spent at the front counter with clients and coworkers.";

/** Every field on a document filled with that value, and every box ticked. */
function filledToTheEdges(document: ReturnType<typeof parseFormDocument>, variant: FormVariant | null) {
  const values: Record<string, string> = {};
  const checked: Record<string, string[]> = {};
  for (const block of renderDocument(document, variant)) {
    if (block.kind === "field") values[block.field.key] = LONG_ANSWER;
    if (block.kind === "field_row") for (const field of block.fields) values[field.key] = LONG_ANSWER;
    if (block.kind === "numbered_list") values[block.key] = LONG_ANSWER;
    if (block.kind === "checkbox_group") checked[block.key] = block.options.map((o) => o.key);
  }
  return { values, checked };
}

describe("nothing is drawn off the paper", () => {
  it("keeps every line of every template inside the right margin, however long the answer", () => {
    for (const template of TEMPLATE_SEEDS) {
      const document = parseFormDocument(template.document);
      const { margin } = pageLayout(document.style?.margins);
      const edge = PAGE.width - margin.right;
      for (const variant of template.variants.length ? template.variants : [null]) {
        const bytes = renderFormPdf(
          document,
          variant,
          filledToTheEdges(document, variant),
          { ...META, templateName: template.name },
        );
        for (const line of drawnLines(bytes)) {
          expect(
            right(line),
            `${template.key}/${variant?.key ?? "-"} page ${line.page + 1}: "${line.text}"`,
          ).toBeLessThanOrEqual(edge + 0.01);
          expect(
            line.x,
            `${template.key}/${variant?.key ?? "-"} page ${line.page + 1}: "${line.text}"`,
          ).toBeGreaterThanOrEqual(margin.left - 0.01);
        }
      }
    }
  });

  it("never prints a label and its value on top of each other", () => {
    /*
     * A label longer than its share of the column used to be drawn in full
     * while the value was positioned at the clamped width, so the answer was
     * written over the question. Two strings on the same baseline must not
     * overlap horizontally.
     */
    for (const template of TEMPLATE_SEEDS) {
      const document = parseFormDocument(template.document);
      for (const variant of template.variants.length ? template.variants : [null]) {
        const bytes = renderFormPdf(
          document,
          variant,
          filledToTheEdges(document, variant),
          { ...META, templateName: template.name },
        );
        const byBaseline = new Map<string, DrawnLine[]>();
        for (const line of drawnLines(bytes)) {
          if (line.text === "") continue;
          const key = `${line.page}:${line.y}`;
          byBaseline.set(key, [...(byBaseline.get(key) ?? []), line]);
        }
        for (const [key, lines] of byBaseline) {
          const ordered = [...lines].sort((a, b) => a.x - b.x);
          for (let index = 1; index < ordered.length; index += 1) {
            expect(
              ordered[index].x,
              `${template.key}/${variant?.key ?? "-"} at ${key}: "${ordered[index - 1].text}" runs into "${ordered[index].text}"`,
            ).toBeGreaterThanOrEqual(right(ordered[index - 1]) - 0.01);
          }
        }
      }
    }
  });

  it("rules under the words rather than through them", () => {
    /*
     * The words have to sit ON the line — the other half of what was reported.
     */
    for (const template of TEMPLATE_SEEDS) {
      const document = parseFormDocument(template.document);
      for (const variant of template.variants.length ? template.variants : [null]) {
        const bytes = renderFormPdf(
          document,
          variant,
          filledToTheEdges(document, variant),
          { ...META, templateName: template.name },
        );
        const rules = drawnRules(bytes);
        for (const line of drawnLines(bytes)) {
          if (line.text.trim() === "") continue;
          for (const rule of rules) {
            if (rule.page !== line.page) continue;
            if (rule.to <= line.x || rule.from >= right(line)) continue;
            const where = `${template.key}/${variant?.key ?? "-"} p${line.page + 1} "${line.text.slice(0, 48)}"`;
            if (rule.y < line.y) {
              expect(line.y - rule.y, `rule crowds the descenders: ${where}`).toBeGreaterThanOrEqual(
                DESCENDER * line.size + CLEAR_BELOW,
              );
            } else {
              expect(rule.y - line.y, `rule above crowds this line: ${where}`).toBeGreaterThanOrEqual(
                ASCENDER * line.size + CLEAR_ABOVE,
              );
            }
          }
        }
      }
    }
  });
});

describe("what must not be split over a page break", () => {
  /**
   * THE FOLD, WALKED ACROSS.
   *
   * A single fixture cannot test a page break: fill every field and the
   * paragraphs land mid-page, where nothing can go wrong. Growing one value a
   * line at a time slides everything below it down the paper, so each block in
   * turn is pushed up to the fold and over it.
   *
   * Checked on the GEOMETRY, not the extracted text. Every page's text ends
   * with the footer, so asking whether a page "ends on a heading" of the
   * extracted string is a question that cannot be answered no matter how badly
   * the page is broken — the first version of this test could not fail.
   */
  const sweep = (document: FormDocument, key: string) => {
    const { contentWidth } = pageLayout(document.style?.margins);
    const blocks = renderDocument(document, null);

    /** The wrapped lines of each block that must not be split, as drawn. */
    const runs = blocks
      .filter((block) => block.kind === "paragraph" || block.kind === "acknowledgement")
      .map((block) =>
        block.kind === "paragraph" || block.kind === "acknowledgement"
          ? wrapText(block.text, contentWidth, SIZE.body, "regular").map(asciiOnly)
          : [],
      )
      .filter((run) => run.length > 1);

    const headings = blocks
      .filter((block) => block.kind === "section")
      .map((block) => (block.kind === "section" ? asciiOnly(block.label) : ""));

    const grown = blocks.find(
      (block) => block.kind === "field" && block.field.input === "long_text",
    );
    const growKey = grown?.kind === "field" ? grown.field.key : null;

    for (let extra = 0; extra < 40; extra += 1) {
      const values = growKey
        ? { [growKey]: `${LONG_ANSWER} ${"one more sentence of detail. ".repeat(extra)}`.trim() }
        : {};
      const bytes = renderFormPdf(document, null, { values, checked: {} }, {
        ...META,
        templateName: key,
      });
      // The footer sits below its own rule at 48; everything above that is the
      // document's own content.
      const body = drawnLines(bytes).filter((line) => line.y > 48);
      const lastPage = Math.max(...body.map((line) => line.page));
      const at = (page: number) => body.filter((line) => line.page === page);

      for (const run of runs) {
        const pages = new Set(
          run.map((text) => body.find((line) => line.text === text)?.page).filter((page) => page !== undefined),
        );
        expect(pages.size, `${key} +${extra}: a paragraph is split over a page break`).toBeLessThanOrEqual(1);
      }

      for (const line of body) {
        if (!headings.includes(line.text)) continue;
        if (line.page === lastPage) continue;
        expect(
          at(line.page).some((other) => other.y < line.y),
          `${key} +${extra}: page ${line.page + 1} ends on the heading "${line.text}"`,
        ).toBe(true);
      }
    }
  };

  for (const template of TEMPLATE_SEEDS) {
    it(`keeps ${template.key} whole wherever the fold lands`, () => {
      sweep(parseFormDocument(template.document), template.key);
    });
  }
});

describe("every template renders", () => {
  it("produces a readable PDF for all nine, empty and filled", async () => {
    for (const template of TEMPLATE_SEEDS) {
      const document = parseFormDocument(template.document);
      const variant = template.variants[0] ?? null;
      const bytes = renderFormPdf(
        document,
        variant,
        { values: {}, checked: {} },
        { ...META, templateName: template.name },
      );
      const { totalPages } = await readBack(bytes);
      expect(totalPages, template.key).toBeGreaterThanOrEqual(1);
    }
  });
});

describe("text layout", () => {
  it("wraps to the column it is given", () => {
    const lines = wrapText("the quick brown fox jumps over the lazy dog", 100, 10, "regular");
    expect(lines.length).toBeGreaterThan(1);
    for (const line of lines) expect(textWidth(line, 10)).toBeLessThanOrEqual(100);
  });

  it("splits a token too wide to fit rather than running off the page", () => {
    const lines = wrapText("supercalifragilisticexpialidocious", 40, 10, "regular");
    expect(lines.length).toBeGreaterThan(1);
    for (const line of lines) expect(textWidth(line, 10)).toBeLessThanOrEqual(40);
  });

  it("keeps deliberate line breaks", () => {
    expect(wrapText("one\ntwo", 500, 10, "regular")).toEqual(["one", "two"]);
  });

  it("folds the characters the standard fonts cannot draw", () => {
    /*
     * No font is embedded, so a curly quote would print as the wrong glyph.
     * Folding to ASCII is visible and correct; leaving it would silently mangle
     * a manager's pasted text.
     */
    expect(asciiOnly("“Don’t — really…”")).toBe('"Don\'t - really..."');
    // The footer separator, which printed as "?" on the first proof.
    expect(asciiOnly("a · b")).toBe("a - b");
    expect(asciiOnly("café")).toBe("caf?");
  });

  it("measures a bold string as wider than the same string regular", () => {
    expect(textWidth("Employee", 10, "bold")).toBeGreaterThan(textWidth("Employee", 10));
  });

  it("wraps bold text to the bold widths, not the regular ones", () => {
    /*
     * THE REGRESSION. Values print bold and used to be wrapped against the
     * regular widths, which are up to 8% narrower — so a wrapped sentence ran
     * past the ruled line it was supposed to sit on, and a long paragraph ran
     * off the right of the page. A line measured in the face it prints in fits
     * the column it was given.
     */
    const sentence =
      "Employees are expected to be in appropriate, professional salon attire " +
      "that meets dress code standards for the entire scheduled shift.";
    for (const line of wrapText(sentence, 504, 10, "bold")) {
      expect(textWidth(line, 10, "bold")).toBeLessThanOrEqual(504);
    }
    // And the old behaviour really did overflow, so the assertion above is
    // measuring something: wrapped regular, drawn bold, a line runs over.
    const drawnBold = wrapText(sentence, 504, 10, "regular").map((line) =>
      textWidth(line, 10, "bold"),
    );
    expect(Math.max(...drawnBold)).toBeGreaterThan(504);
  });
});

describe("naming the download", () => {
  it("names it after the form, the employee and the date", () => {
    expect(pdfFileName(META)).toBe("Coaching-Form-Jordan-Vance-2026-09-04.pdf");
  });

  it("takes the title from the document, resolved for the variant", () => {
    const document = parseFormDocument(seed("sdit-epp").document);
    expect(documentTitle(document, seed("sdit-epp").variants[0])).toBe(
      "Employee Performance Plan - SDIT",
    );
  });
});
