import { extractText, getDocumentProxy } from "unpdf";
import { describe, expect, it } from "vitest";

import { parseFormDocument } from "./document";
import { TEMPLATE_SEEDS, DMIT_VARIANTS } from "./library";
import {
  asciiOnly,
  documentTitle,
  pdfFileName,
  renderFormPdf,
  textWidth,
  wrapText,
  type RenderMeta,
} from "./pdf-render";

/**
 * THE PRINTED FORM, READ BACK OUT OF THE PDF IT PRODUCED.
 *
 * Every assertion here parses the generated bytes with the same library the
 * uploader uses, so what is being checked is the actual document a manager
 * downloads — not the intention of the code that drew it.
 *
 * The two that matter most are negative: no editor furniture on the page, and
 * nothing on a signature line. Those are the ways a form stops being a usable
 * business record.
 */

const seed = (key: string) => {
  const found = TEMPLATE_SEEDS.find((entry) => entry.key === key);
  if (!found) throw new Error(`no seed ${key}`);
  return found;
};

const META: RenderMeta = {
  templateName: "Coaching Form",
  templateVersion: 1,
  employeeName: "Jordan Vance",
  formDate: "2026-09-04",
  locationName: "Invented Store Alpha",
  reference: "form-0001",
  status: "finalized",
};

async function readBack(bytes: Uint8Array) {
  const pdf = await getDocumentProxy(bytes);
  const { text, totalPages } = await extractText(pdf, { mergePages: true });
  return { text, totalPages };
}

describe("a rendered coaching form", () => {
  const document = parseFormDocument(seed("coaching").document);
  const values = {
    values: {
      employee_name: "Jordan Vance",
      form_date: "2026-09-04",
      job_title: "Tanning Consultant",
      location: "Invented Store Alpha",
      coaching_details:
        "Observed three tours where the membership options were not offered. Agreed to shadow two tours daily this week.",
      other_topic: "",
    },
    checked: {
      coaching_type: ["under_performance"],
      coaching_topics: ["salon_tours", "selling_memberships"],
    },
  };

  it("is a readable PDF", async () => {
    const bytes = renderFormPdf(document, null, values, META);
    expect(new TextDecoder().decode(bytes.subarray(0, 8))).toContain("%PDF-");
    const { totalPages } = await readBack(bytes);
    expect(totalPages).toBeGreaterThanOrEqual(1);
  });

  it("prints the corporate document, not the editor", async () => {
    const bytes = renderFormPdf(document, null, values, META);
    const { text } = await readBack(bytes);

    // The document itself.
    expect(text).toContain("SUN TAN CITY");
    expect(text).toContain("Coaching Form");
    expect(text).toContain("Employee Information");
    expect(text).toContain("Type Of Coaching");
    expect(text).toContain("Jordan Vance");
    expect(text).toContain("membership options were not offered");

    // THE EDITOR'S FURNITURE MUST NOT BE THERE. These are the chips and copy an
    // administrator sees on screen; on a signed HR record they would be noise
    // at best and misleading at worst.
    for (const forbidden of [
      "AI FILLS",
      "FILLED BY HAND",
      "Ask Sunny fills",
      "Edit template",
      "STANDARD FORM",
      "All templates",
      "Select text to format",
      "Replace with new PDF",
    ]) {
      expect(text, `"${forbidden}" leaked onto the page`).not.toContain(forbidden);
    }
  });

  it("marks the ticked boxes and leaves the others empty", async () => {
    const bytes = renderFormPdf(document, null, values, META);
    const { text } = await readBack(bytes);
    // Every option prints, ticked or not — a checkbox list with the unticked
    // options removed is not the same form.
    expect(text).toContain("Under Performance");
    expect(text).toContain("Re-Training");
    expect(text).toContain("Salon Tours");
    expect(text).toContain("Lotion Basics");
  });

  it("leaves the signature lines blank, with nothing to fill them", async () => {
    const bytes = renderFormPdf(document, null, values, META);
    const { text } = await readBack(bytes);
    expect(text).toContain("Employee Signature");
    expect(text).toContain("Supervisor Signature");
    // The captions are there; the employee's name never appears ON one, because
    // a signature block carries no field key at all.
    expect(text).not.toContain("Jordan Vance Employee Signature");
  });

  it("footers every page with the template version and the page count", async () => {
    const bytes = renderFormPdf(document, null, values, META);
    const { text } = await readBack(bytes);
    expect(text).toContain("Template v1");
    expect(text).toMatch(/Page 1 of \d/);
  });

  it("says DRAFT on a draft and not on a finalized form", async () => {
    const draft = renderFormPdf(document, null, values, { ...META, status: "draft" });
    const finalized = renderFormPdf(document, null, values, META);
    expect((await readBack(draft)).text).toContain("DRAFT");
    expect((await readBack(finalized)).text).not.toContain("DRAFT");
  });
});

describe("the six-page DMIT EPP", () => {
  const document = parseFormDocument(seed("dmit-epp-tsd").document);

  it("prints the reviewed position for the chosen variant, and only that one", async () => {
    const tsd = renderFormPdf(
      document,
      DMIT_VARIANTS[0],
      { values: {}, checked: {} },
      { ...META, templateName: "DMIT EPP — TSD Review" },
    );
    const { text } = await readBack(tsd);

    expect(text).toContain("District Manager");
    // The DMIT reading's own description must not appear on a TSD review.
    expect(text).not.toContain("District Manager in Training is learning");
  });

  it("resolves every role placeholder", async () => {
    const bytes = renderFormPdf(document, DMIT_VARIANTS[1], { values: {}, checked: {} }, META);
    const { text } = await readBack(bytes);
    expect(text).not.toContain("{{role}}");
    expect(text).not.toContain("{{roleAbbr}}");
  });

  it("keeps its explicit page breaks and reaches the re-evaluation", async () => {
    const bytes = renderFormPdf(document, DMIT_VARIANTS[0], { values: {}, checked: {} }, META);
    const { text, totalPages } = await readBack(bytes);
    expect(totalPages).toBeGreaterThanOrEqual(3);
    expect(text).toContain("Follow-up");
    expect(text).toContain("Re-Evaluation");
    // Both acknowledgements, because the second one belongs to the
    // re-evaluation and losing it would lose the record of that meeting.
    expect(text.match(/Acknowledgement/g)?.length ?? 0).toBeGreaterThanOrEqual(2);
  });

  it("prints the hand-filled section as empty ruled lines", async () => {
    const bytes = renderFormPdf(document, DMIT_VARIANTS[0], { values: {}, checked: {} }, META);
    const { text } = await readBack(bytes);
    expect(text).toContain("What are your overall top three strengths?");
    expect(text).toContain("This section is completed by hand");
  });
});

describe("every template renders", () => {
  it("produces a readable PDF for all nine, empty and filled", async () => {
    for (const template of TEMPLATE_SEEDS) {
      const document = parseFormDocument(template.document);
      const variant = template.variants[0] ?? null;
      const bytes = renderFormPdf(
        document,
        variant,
        { values: {}, checked: {} },
        { ...META, templateName: template.name },
      );
      const { totalPages } = await readBack(bytes);
      expect(totalPages, template.key).toBeGreaterThanOrEqual(1);
    }
  });
});

describe("text layout", () => {
  it("wraps to the column it is given", () => {
    const lines = wrapText("the quick brown fox jumps over the lazy dog", 100, 10);
    expect(lines.length).toBeGreaterThan(1);
    for (const line of lines) expect(textWidth(line, 10)).toBeLessThanOrEqual(100);
  });

  it("splits a token too wide to fit rather than running off the page", () => {
    const lines = wrapText("supercalifragilisticexpialidocious", 40, 10);
    expect(lines.length).toBeGreaterThan(1);
    for (const line of lines) expect(textWidth(line, 10)).toBeLessThanOrEqual(40);
  });

  it("keeps deliberate line breaks", () => {
    expect(wrapText("one\ntwo", 500, 10)).toEqual(["one", "two"]);
  });

  it("folds the characters the standard fonts cannot draw", () => {
    /*
     * No font is embedded, so a curly quote would print as the wrong glyph.
     * Folding to ASCII is visible and correct; leaving it would silently mangle
     * a manager's pasted text.
     */
    expect(asciiOnly("“Don’t — really…”")).toBe('"Don\'t - really..."');
    // The footer separator, which printed as "?" on the first proof.
    expect(asciiOnly("a · b")).toBe("a - b");
    expect(asciiOnly("café")).toBe("caf?");
  });

  it("measures a bold string as wider than the same string regular", () => {
    expect(textWidth("Employee", 10, "bold")).toBeGreaterThan(textWidth("Employee", 10));
  });
});

describe("naming the download", () => {
  it("names it after the form, the employee and the date", () => {
    expect(pdfFileName(META)).toBe("Coaching-Form-Jordan-Vance-2026-09-04.pdf");
  });

  it("takes the title from the document, resolved for the variant", () => {
    const document = parseFormDocument(seed("sdit-epp").document);
    expect(documentTitle(document, seed("sdit-epp").variants[0])).toBe(
      "Employee Performance Plan - SDIT",
    );
  });
});
